create database  Company;
CREATE TABLE Departments(

    DEPT_ID int IDENTITY(1,1) PRIMARY KEY,

    DEPT_NAME varchar(10) NOT NULL
 
);

INSERT INTO Departments(DEPT_NAME) VALUES('HR');
INSERT INTO Departments(DEPT_NAME) VALUES('SOFTWARE');
INSERT INTO Departments(DEPT_NAME) VALUES('ADMIN');
INSERT INTO Departments(DEPT_NAME) VALUES('PAYROLL');
INSERT INTO Departments(DEPT_NAME) VALUES('SECURITY');
INSERT INTO Departments(DEPT_NAME) VALUES('INFO');

SELECT * FROM Departments;


UPDATE Departments
SET DEPT_NAME='FINANCE'
WHERE DEPT_NAME='PAYROLL';

CREATE TABLE BRANCHES(

    BID int PRIMARY KEY,

    BRACH_NAME nchar(10)
);
INSERT INTO BRANCHES(BID,BRACH_NAME) VALUES(1,'MUMBAI');
INSERT INTO BRANCHES(BID,BRACH_NAME) VALUES(2,'DELHI');
INSERT INTO BRANCHES(BID,BRACH_NAME) VALUES(3,'CHENNAI');
INSERT INTO BRANCHES(BID,BRACH_NAME) VALUES(4,'KOLKATA');

SELECT * FROM BRANCHES;
